version: "3"

networks:
  site1:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
          gateway: 10.1.0.1
        - subnet: 2001:3200:3201::/64
          gateway: 2001:3200:3201::1
  site2:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
          gateway: 10.2.0.1
        - subnet: 2001:3200:3202::/64
          gateway: 2001:3200:3202::1

services:
  site-1-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    build:
      context: ../..
      dockerfile: Dockerfile
    networks:
      site1:
        ipv4_address: 10.1.0.2
        ipv6_address: 2001:3200:3201::2
    hostname: site-1-node
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --bootstrap.default-network-policy=accept
      - --bootstrap.mesh-domain=site-1.internal
      - --raft.in-memory

  site-2-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    build:
      context: ../..
      dockerfile: Dockerfile
    networks:
      site2:
        ipv4_address: 10.2.0.2
        ipv6_address: 2001:3200:3202::2
    hostname: site-2-node
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --bootstrap.default-network-policy=accept
      - --bootstrap.mesh-domain=site-2.internal
      - --raft.in-memory

  bridge-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    build:
      context: ../..
      dockerfile: Dockerfile
    networks:
      site1:
        ipv4_address: 10.1.0.3
        ipv6_address: 2001:3200:3201::3
      site2:
        ipv4_address: 10.2.0.3
        ipv6_address: 2001:3200:3202::3
    hostname: bridge-node
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    ports:
      - 6061:6061
      - 6062:6062
      - 6363:5353/udp
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      # Site 1 Options
      - --bridge.site-1.mesh.join-address=site-1-node:8443
      - --bridge.site-1.raft.in-memory
      - --bridge.site-1.wireguard.listen-port=51821
      - --bridge.site-1.services.listen-address=:8443
      - --bridge.site-1.raft.listen-address=:9443
      - --bridge.site-1.plugins.debug.listen-address=:6061
      - --bridge.site-1.plugins.debug.enable-db-querier=true
      # Site 2 Options
      - --bridge.site-2.mesh.join-address=site-2-node:8443
      - --bridge.site-2.raft.in-memory
      - --bridge.site-2.services.listen-address=:8444
      - --bridge.site-2.wireguard.listen-port=51822
      - --bridge.site-2.raft.listen-address=:9444
      - --bridge.site-2.plugins.debug.listen-address=:6062
      - --bridge.site-2.plugins.debug.enable-db-querier=true
      # Bridged DNS Options
      - --bridge.services.meshdns.enabled
      - --bridge.services.meshdns.listen-udp=:5353
      - --bridge.use-meshdns
