version: '3'

networks:
  public-net:
    ipam:
      driver: default
      config:
        - subnet: 10.250.0.0/24
          gateway: 10.250.0.100
  ice-net:
    ipam:
      driver: default
      config:
        - subnet: 10.251.0.0/24
          gateway: 10.251.0.100
  site-1:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
  site-2:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
  site-3:
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.0/24

volumes:
  site-1-leader:
  site-2-leader:
  site-3-leader:

services:
  
  # TURN Node

  turn-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      ice-net:
        ipv4_address: 10.251.0.1
      public-net:
    hostname: turn-node
    entrypoint:
      - /node
      - --global.log-level=debug
      - --global.insecure
      - --global.no-ipv6
      - --global.primary-endpoint=10.251.0.1
      - --global.detect-private-endpoints
      - --services.api.leader-proxy
      - --services.api.webrtc
      - --services.api.stun-servers=stun:10.251.0.1:3478
      - --services.turn.enabled
      - --services.turn.public-ip=10.251.0.1
      - --mesh.join-address=site-1-leader:8443
      - --mesh.max-join-retries=10
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
      
  # Site 1

  site-1-leader:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
        ipv4_address: 10.250.0.1
      site-1:
      ice-net:
    hostname: site-1-leader
    entrypoint:
      - /node
      - --global.log-level=debug
      - --global.insecure
      - --global.no-ipv6
      - --global.primary-endpoint=10.250.0.1
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --bootstrap.advertise-address=site-1-leader:9443
      - --bootstrap.servers=site-1-leader=site-1-leader:9443,site-2-leader=site-2-leader:9443,site-3-leader=site-3-leader:9443
      - --bootstrap.ipv4-network=10.10.10.0/24
      - --bootstrap.default-network-policy=accept
      - --raft.data-dir=/data
      - --mesh.zone-awareness-id=site-1
      - --services.api.leader-proxy
      - --services.api.mesh
      - --services.api.admin
      - --services.api.webrtc
      - --services.mesh-dns.enabled
      - --services.dashboard.enabled
      - --services.dashboard.listen-address=:8080
      - --wireguard.key-file=/data/wireguard.key
    ports:
      - 8080:8080
      - 8443:8443
      - 5354:5353/udp
    volumes:
      - site-1-leader:/data
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  site-1-follower:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      site-1:
      ice-net:
    hostname: site-1-follower
    entrypoint:
      - /node
      - --global.insecure
      - --global.no-ipv6
      - --raft.in-memory
      - --mesh.join-address=site-1-leader:8443
      - --mesh.max-join-retries=10
      - --mesh.zone-awareness-id=site-1
      - --mesh.direct-peers=site-2-follower,site-3-follower
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  # Site 2

  site-2-leader:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
        ipv4_address: 10.250.0.2
      site-2:
      ice-net:
    hostname: site-2-leader
    entrypoint:
      - /node
      - --global.insecure
      - --global.no-ipv6
      - --global.primary-endpoint=10.250.0.2
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --bootstrap.advertise-address=site-2-leader:9443
      - --bootstrap.servers=site-1-leader=site-1-leader:9443,site-2-leader=site-2-leader:9443,site-3-leader=site-3-leader:9443
      - --bootstrap.ipv4-network=10.10.10.0/24
      - --bootstrap.default-network-policy=accept
      - --raft.data-dir=/data
      - --mesh.zone-awareness-id=site-2
      - --services.api.leader-proxy
      - --services.api.mesh
      - --services.api.webrtc
      - --wireguard.key-file=/data/wireguard.key
    volumes:
      - site-2-leader:/data
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  site-2-follower:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      site-2:
      ice-net:
    hostname: site-2-follower
    entrypoint:
      - /node
      - --global.insecure
      - --global.no-ipv6
      - --raft.in-memory
      - --mesh.join-address=site-2-leader:8443
      - --mesh.max-join-retries=15
      - --mesh.zone-awareness-id=site-2
      - --mesh.direct-peers=site-1-follower,site-3-follower
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  # Site 3

  site-3-leader:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
        ipv4_address: 10.250.0.3
      site-3:
      ice-net:
    hostname: site-3-leader
    entrypoint:
      - /node
      - --global.insecure
      - --global.no-ipv6
      - --global.primary-endpoint=10.250.0.3
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --bootstrap.advertise-address=site-3-leader:9443
      - --bootstrap.servers=site-1-leader=site-1-leader:9443,site-2-leader=site-2-leader:9443,site-3-leader=site-3-leader:9443
      - --bootstrap.ipv4-network=10.10.10.0/24
      - --bootstrap.default-network-policy=accept
      - --raft.data-dir=/data
      - --mesh.zone-awareness-id=site-3
      - --services.api.leader-proxy
      - --services.api.mesh
      - --services.api.webrtc
      - --wireguard.key-file=/data/wireguard.key
    volumes:
      - site-3-leader:/data
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  site-3-follower:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      site-3:
      ice-net:
    hostname: site-3-follower
    entrypoint:
      - /node
      - --global.insecure
      - --global.no-ipv6
      - --raft.in-memory
      - --mesh.join-address=site-3-leader:8443
      - --mesh.max-join-retries=15
      - --mesh.zone-awareness-id=site-3
      - --mesh.direct-peers=site-1-follower,site-2-follower
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
