project_name: webmesh

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: node
    main: cmd/node/main.go
    binary: webmesh-node
    env:
      - CGO_ENABLED=0
    tags:
      - osusergo
      - netgo
    ldflags:
      - -s -w 
      - -X github.com/webmeshproj/node/pkg/version.Version={{.Version}}
      - -X github.com/webmeshproj/node/pkg/version.Commit={{.Commit}}
      - -X github.com/webmeshproj/node/pkg/version.BuildDate={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - '386'
      - ppc64le
      - s390x
      - mips64le
      - mips64
      - mipsle
      - mips

  - id: node-docker-linux
    main: cmd/node/main.go
    binary: webmesh-node
    env:
      - CGO_ENABLED=0
    tags:
      - osusergo
      - netgo
    ldflags:
      - -s -w 
      - -X github.com/webmeshproj/node/pkg/version.Version={{.Version}}
      - -X github.com/webmeshproj/node/pkg/version.Commit={{.Commit}}
      - -X github.com/webmeshproj/node/pkg/version.BuildDate={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: wmctl
    main: cmd/wmctl/main.go
    binary: wmctl
    env:
      - CGO_ENABLED=0
    tags:
      - osusergo
      - netgo
    ldflags:
      - -s -w 
      - -X github.com/webmeshproj/node/pkg/version.Version={{.Version}}
      - -X github.com/webmeshproj/node/pkg/version.Commit={{.Commit}}
      - -X github.com/webmeshproj/node/pkg/version.BuildDate={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - '386'
      - ppc64le
      - s390x
      - mips64le
      - mips64
      - mipsle
      - mips

upx:
  - enabled: true
    compress: best
    lzma: true
    goos: 
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - '386'
      - ppc64le
      - mips
      - mipsle
    ids:
      - node
      - wmctl

  - enabled: true
    compress: best
    lzma: true
    goos: 
      - darwin
    goarch:
      - amd64
    ids:
      - node
      - wmctl

  - enabled: true
    compress: best
    lzma: true
    goos: 
      - windows
    goarch:
      - amd64
      - '386'
    ids:
      - node
      - wmctl

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

archives:
  - id: webmesh
    format: tar.gz
    builds:
      - node
      - wmctl
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

brews:
  - ids: [webmesh]
    folder: Formula
    homepage: https://webmeshproj.github.io
    description: WebMesh is a service mesh for the web
    license: Apache 2.0
    url_template: "https://github.com/webmeshproj/node/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    skip_upload: auto
    repository:
      owner: webmeshproj
      name: homebrew-repo
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: Avi Zimmerman
      email: avi.zimmerman@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    test: |
      system "#{bin}/webmesh-node --version"
      system "#{bin}/wmctl --version"

nfpms:
  - id: webmesh
    maintainer: Avi Zimmerman <avi.zimmerman@gmail.com>
    description: WebMesh is a service mesh for the web
    homepage: https://webmeshproj.github.io
    license: Apache 2.0
    builds:
      - node
      - wmctl
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    recommends:
      - wireguard-tools
    archlinux:
      packager: Avi Zimmerman <avi.zimmerman@gmail.com>
      pkgbase: webmesh
    overrides:
      rpm:
        dependencies:
          - elrepo-release
          - epel-release
          - kmod-wireguard

# chocolateys:
#   - ids: [webmesh]
#     summary: WebMesh is a service mesh for the web
#     description: |
#       {{ .ProjectName }} installer package.
#       WebMesh is a service mesh for the web
#     owners: Webmesh Project
#     authors: Avi Zimmerman
#     project_url: https://webmeshproj.github.io
#     docs_url: https://webmeshproj.github.io
#     bug_tracker_url: "https://github.com/webmeshproj/node/issues"
#     url_template: "https://github.com/webmeshproj/node/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#     copyright: 2023 Avi Zimmerman
#     license_url: https://github.com/webmeshproj/node/blob/main/LICENSE
#     require_license_acceptance: false
#     project_source_url: https://github.com/webmeshproj/node
#     release_notes: "https://github.com/webmeshproj/node/releases/tag/v{{ .Version }}"
#     api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - "sign-blob"
      - "--yes"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "--output-signature=${signature}"
      - "--output-certificate=${signature}.cert"
      - "${artifact}"
    artifacts: checksum

changelog:
  sort: asc
  filters:
    exclude:
      - '^examples:'

release:
  github:
    owner: webmeshproj
    name: node
  ids:
    - webmesh
  extra_files:
    - glob: dist/*.sig
    - glob: dist/*.sig.cert

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
