project_name: webmesh

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: node
    main: cmd/node/main.go
    binary: webmesh-node
    env:
      - CGO_ENABLED=0
    tags:
      - osusergo
      - netgo
    ldflags:
      - -s -w 
      - -X github.com/webmeshproj/$(NAME)/pkg/version.Version={{.Version}}
      - -X github.com/webmeshproj/$(NAME)/pkg/version.Commit={{.Commit}}
      - -X github.com/webmeshproj/$(NAME)/pkg/version.BuildDate={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - '386'
      - ppc64le
      - s390x
      - mips64le
      - mips64
      - mipsle
      - mips

  - id: node-docker-linux
    main: cmd/node/main.go
    binary: webmesh-node
    env:
      - CGO_ENABLED=0
    tags:
      - osusergo
      - netgo
    ldflags:
      - -s -w 
      - -X github.com/webmeshproj/$(NAME)/pkg/version.Version={{.Version}}
      - -X github.com/webmeshproj/$(NAME)/pkg/version.Commit={{.Commit}}
      - -X github.com/webmeshproj/$(NAME)/pkg/version.BuildDate={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64

  - id: wmctl
    main: cmd/wmctl/main.go
    binary: wmctl
    env:
      - CGO_ENABLED=0
    tags:
      - osusergo
      - netgo
    ldflags:
      - -s -w 
      - -X github.com/webmeshproj/$(NAME)/pkg/version.Version={{.Version}}
      - -X github.com/webmeshproj/$(NAME)/pkg/version.Commit={{.Commit}}
      - -X github.com/webmeshproj/$(NAME)/pkg/version.BuildDate={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - '386'
      - ppc64le
      - s390x
      - mips64le
      - mips64
      - mipsle
      - mips

upx:
  - enabled: true
    compress: best
    lzma: true
    goos: 
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - '386'
      - ppc64le
      - mips
      - mipsle
    ids:
      - node
      - wmctl

  - enabled: true
    compress: best
    lzma: true
    goos: 
      - darwin
    goarch:
      - amd64
    ids:
      - node
      - wmctl

  - enabled: true
    compress: best
    lzma: true
    goos: 
      - windows
    goarch:
      - amd64
      - '386'
    ids:
      - node
      - wmctl

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - "sign-blob"
      - "--yes"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "--output-signature=${signature}"
      - "${artifact}"
    artifacts: all

archives:
  - format: tar.gz
    builds:
      - node
      - wmctl
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - maintainer: Avi Zimmerman <avi.zimmerman@gmail.com>
    description: WebMesh is a service mesh for the web
    homepage: https://webmeshproj.github.io
    license: Apache 2.0
    builds:
      - node
      - wmctl
    formats:
      - deb
      - rpm
      - apk

changelog:
  sort: asc
  filters:
    exclude:
      - '^examples:'

release:
  github:
    owner: webmeshproj
    name: node
  ids:
    - node
    - wmctl

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
