version: '3'

networks:
  bootstrap:
    # enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
          gateway: 10.1.0.100
        # - subnet: 2001:db8:1::/64
        #   gateway: 2001:db8:1::1

services:

  bootstrap-node-1:
    image: ${IMAGE:-gitlab.com/webmesh/node:latest}
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      - /node
      - --global.insecure
      - --global.no-ipv6
      - --global.log-level=debug
      - --global.endpoint=10.1.0.1
      - --store.bootstrap
      - --store.node-id=bootstrap-node-1
      - --store.bootstrap-servers=bootstrap-node-1=10.1.0.1:9443,bootstrap-node-2=10.1.0.2:9443,bootstrap-node-3=10.1.0.3:9443
      - --store.data-dir=/data
      - --store.raft-log-format=json
      - --store.raft-log-level=debug
      - --wireguard.no-modprobe
      - --grpc.enable-metrics
    ports:
      - 8443:8443
    volumes:
      - /lib/modules:/lib/modules
      - bootstrap-node-1:/data
    networks:
      bootstrap:
        ipv4_address: 10.1.0.1
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  bootstrap-node-2:
    image: ${IMAGE:-gitlab.com/webmesh/node:latest}
    entrypoint:
      - /node
      - --global.insecure
      - --global.no-ipv6
      - --global.log-level=debug
      - --global.endpoint=10.1.0.2
      - --store.bootstrap
      - --store.node-id=bootstrap-node-2
      - --store.bootstrap-servers=bootstrap-node-1=10.1.0.1:9443,bootstrap-node-2=10.1.0.2:9443,bootstrap-node-3=10.1.0.3:9443
      - --store.data-dir=/data
      - --store.raft-log-format=json
      - --store.raft-log-level=debug
      - --wireguard.no-modprobe
      - --grpc.enable-metrics
    volumes:
      - /lib/modules:/lib/modules
      - bootstrap-node-2:/data
    ports:
      - 8444:8443
    networks:
      bootstrap:
        ipv4_address: 10.1.0.2
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  bootstrap-node-3:
    image: ${IMAGE:-gitlab.com/webmesh/node:latest}
    entrypoint:
      - /node
      - --global.insecure
      - --global.no-ipv6
      - --global.log-level=debug
      - --global.endpoint=10.1.0.3
      - --store.bootstrap
      - --store.node-id=bootstrap-node-3
      - --store.bootstrap-servers=bootstrap-node-1=10.1.0.1:9443,bootstrap-node-2=10.1.0.2:9443,bootstrap-node-3=10.1.0.3:9443
      - --store.data-dir=/data
      - --store.raft-log-format=json
      - --store.raft-log-level=debug
      - --wireguard.no-modprobe
      - --grpc.enable-metrics
    volumes:
      - /lib/modules:/lib/modules
      - bootstrap-node-3:/data
    ports:
      - 8445:8443
    networks:
      bootstrap:
        ipv4_address: 10.1.0.3
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

volumes:
  bootstrap-node-1:
  bootstrap-node-2:
  bootstrap-node-3:
