version: '3'

networks:
  bootstrap:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
          gateway: 10.1.0.100

services:

  bootstrap-node-1:
    image: ${IMAGE:-gitlab.com/webmesh/node:latest}
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      bootstrap:
        ipv4_address: 10.1.0.1
    hostname: bootstrap-node-1
    entrypoint:
      - /node
      - --global.insecure
      - --global.no-ipv6
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --store.node-additional-endpoints=127.0.0.1
      - --store.bootstrap
      - --store.bootstrap-servers=bootstrap-node-1=10.1.0.1:9443,bootstrap-node-2=10.1.0.2:9443,bootstrap-node-3=10.1.0.3:9443
      - --store.bootstrap-ipv4-network=10.10.10.0/24
      - --store.data-dir=/data
      - --store.snapshot-threshold=10
      - --services.enable-leader-proxy
      - --services.enable-peer-discovery-api
      - --services.enable-metrics
      - --services.enable-mesh-api
      - --services.enable-webrtc-api
      - --services.enable-turn-server
      - --services.enable-mesh-dns
      - --services.turn-server-public-ip=127.0.0.1
      - --services.stun-port-range=60000-60001
      - --services.exclusive-turn-server
    ports:
      - 8443:8443
      - 3478:3478
      - 5354:5353/udp
      - 51820:51820/udp
      - 60000-60001:60000-60001/udp
      - 60000-60001:60000-60001/tcp
    volumes:
      - bootstrap-node-1:/data
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  bootstrap-node-2:
    image: ${IMAGE:-gitlab.com/webmesh/node:latest}
    networks:
      bootstrap:
        ipv4_address: 10.1.0.2
    hostname: bootstrap-node-2
    entrypoint:
      - /node
      - --global.insecure
      - --global.no-ipv6
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --store.bootstrap
      - --store.bootstrap-servers=bootstrap-node-1=10.1.0.1:9443,bootstrap-node-2=10.1.0.2:9443,bootstrap-node-3=10.1.0.3:9443
      - --store.bootstrap-ipv4-network=10.10.10.0/24
      - --store.data-dir=/data
      - --services.enable-leader-proxy
    volumes:
      - bootstrap-node-2:/data
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  bootstrap-node-3:
    image: ${IMAGE:-gitlab.com/webmesh/node:latest}
    networks:
      bootstrap:
        ipv4_address: 10.1.0.3
    hostname: bootstrap-node-3
    entrypoint:
      - /node
      - --global.insecure
      - --global.no-ipv6
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --store.bootstrap
      - --store.bootstrap-servers=bootstrap-node-1=10.1.0.1:9443,bootstrap-node-2=10.1.0.2:9443,bootstrap-node-3=10.1.0.3:9443
      - --store.bootstrap-ipv4-network=10.10.10.0/24
      - --store.data-dir=/data
      - --services.enable-leader-proxy
    volumes:
      - bootstrap-node-3:/data
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

volumes:
  bootstrap-node-1:
  bootstrap-node-2:
  bootstrap-node-3:
