version: "3"

networks:
  bootstrap:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
          gateway: 10.1.0.100

services:
  bootstrap-node-1:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    build:
      context: ../..
      dockerfile: Dockerfile
    networks:
      bootstrap:
        ipv4_address: 10.1.0.1
    hostname: bootstrap-node-1
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --bootstrap.servers=bootstrap-node-1=10.1.0.1:9443,bootstrap-node-2=10.1.0.2:9443,bootstrap-node-3=10.1.0.3:9443
      - --bootstrap.ipv4-network=10.10.10.0/24
      - --bootstrap.default-network-policy=accept
      - --raft.in-memory
      - --services.campfire.enabled
      - --services.campfire.listen-udp=:4095
    ports:
      - 4095:4095/udp
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  bootstrap-node-2:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      bootstrap:
        ipv4_address: 10.1.0.2
    hostname: bootstrap-node-2
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --bootstrap.servers=bootstrap-node-1=10.1.0.1:9443,bootstrap-node-2=10.1.0.2:9443,bootstrap-node-3=10.1.0.3:9443
      - --bootstrap.ipv4-network=10.10.10.0/24
      - --bootstrap.default-network-policy=accept
      - --raft.in-memory
      - --services.campfire.enabled
      - --services.campfire.listen-udp=:4096
    ports:
      - 4096:4096/udp
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  bootstrap-node-3:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      bootstrap:
        ipv4_address: 10.1.0.3
    hostname: bootstrap-node-3
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --bootstrap.servers=bootstrap-node-1=10.1.0.1:9443,bootstrap-node-2=10.1.0.2:9443,bootstrap-node-3=10.1.0.3:9443
      - --bootstrap.ipv4-network=10.10.10.0/24
      - --bootstrap.default-network-policy=accept
      - --raft.in-memory
      - --services.campfire.enabled
      - --services.campfire.listen-udp=:4097
    ports:
      - 4097:4097/udp
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
