version: '3'

networks:
  simple:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
          # Gateway is the same address as the host
          gateway: 10.1.0.1

volumes:
  bootstrap-node:

services:

  bootstrap-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    build:
      context: ../..
      dockerfile: Dockerfile
    networks:
      simple:
    hostname: bootstrap-node
    entrypoint:
      - /node
      - --global.insecure
      - --global.no-ipv6
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --global.log-level=debug
      - --bootstrap.enabled
      - --bootstrap.default-network-policy=accept
      - --raft.data-dir=/data
      - --wireguard.key-file=/data/wireguard.key
      - --plugins.server=server=10.1.0.1:8081,insecure=true
    volumes:
      - bootstrap-node:/data
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  join-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      simple:
    hostname: join-node
    entrypoint:
      - /node
      - --global.insecure
      - --global.no-ipv6
      - --raft.in-memory
      - --mesh.join-address=bootstrap-node:8443
      - --mesh.max-join-retries=15
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
