version: '3'

networks:
  simple:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24

volumes:
  bootstrap-node:

services:

  bootstrap-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    build:
      context: ../..
      dockerfile: Dockerfile
    networks:
      simple:
        ipv4_address: 10.1.0.2
    hostname: bootstrap-node-1
    entrypoint:
      - /node
      - --global.insecure
      - --global.no-ipv6
      - --global.detect-endpoints
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --raft.data-dir=/data
    ports:
      - 8443:8443
      - 51820:51820/udp
    volumes:
      - bootstrap-node:/data
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  join-node:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      simple:
    hostname: join-node
    entrypoint:
      - /node
      - --global.insecure
      - --global.no-ipv6
      - --raft.in-memory
      - --mesh.join-address=10.1.0.2:8443
      - --mesh.max-join-retries=15
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
