name: CI
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

env:
  ALPINE_IMAGE_NAME: ghcr.io/webmeshproj/node
  DISTROLESS_IMAGE_NAME: ghcr.io/webmeshproj/node-distroless
  GO_VERSION: ^1.20
  PLATFORMS: linux/amd64,linux/arm64,linux/arm

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache-dependency-path: go.sum

      - name: Setup GOPRIVATE
        shell: bash
        run: |
          echo "GOPRIVATE=github.com/webmeshproj" >> $GITHUB_ENV
          git config --global \
            url."https://oauth2:${{ secrets.GOPRIVATE_TOKEN }}@github.com".insteadOf \
            https://github.com

      - name: Download Go Modules
        shell: bash
        run: go mod download -x

      - name: Run linting
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.2
          args: --timeout 10m
          skip-pkg-cache: true

  build-publish:
    name: Build and Publish Artifacts
    runs-on: ubuntu-latest
    needs: [tests]
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache-dependency-path: go.sum

      - name: Setup GOPRIVATE
        shell: bash
        run: |
          echo "GOPRIVATE=github.com/webmeshproj" >> $GITHUB_ENV
          git config --global \
            url."https://oauth2:${{ secrets.GOPRIVATE_TOKEN }}@github.com".insteadOf \
            https://github.com

      - name: Download Go Modules
        shell: bash
        run: go mod download -x

      - name: Setup Cosign
        uses: sigstore/cosign-installer@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Cross Compiler Image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.build
          tags: ghcr.io/webmeshproj/node-buildx
          push: false
          cache-to: type=gha
          cache-from: type=gha

      - name: Build Release Binaries
        shell: bash
        env:
          BUILD_IMAGE: ghcr.io/webmeshproj/node-buildx
        run: make dist

      - name: Login to GHCR
        uses: docker/login-action@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Get Image Tags
        shell: bash
        id: tags
        run: |
          ALPINE_IMAGES="${ALPINE_IMAGE_NAME}:latest,${ALPINE_IMAGE_NAME}:${{ github.sha }}"
          DISTROLESS_IMAGES="${DISTROLESS_IMAGE_NAME}:latest,${DISTROLESS_IMAGE_NAME}:${{ github.sha }}"
          if [[ ${{ github.ref_name }} =~ ^v.* ]] ; then
            ALPINE_IMAGES+=",${ALPINE_IMAGE_NAME}:${{ github.ref_name }}"
            DISTROLESS_IMAGES+=",${DISTROLESS_IMAGE_NAME}:${{ github.ref_name }}"
          fi
          echo "alpine-images=${ALPINE_IMAGES}" >> "${GITHUB_OUTPUT}"
          echo "distroless-images=${DISTROLESS_IMAGES}" >> "${GITHUB_OUTPUT}"

      - name: Build and Push Alpine Images
        uses: docker/build-push-action@v3
        id: alpine-build
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.tags.outputs.alpine-images }}
          platforms: ${{ env.PLATFORMS }}
          cache-to: type=gha
          cache-from: type=gha

      - name: Build and Push Distroless Images
        uses: docker/build-push-action@v3
        id: distroless-build
        with:
          context: .
          file: Dockerfile.distroless
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.tags.outputs.distroless-images }}
          platforms: ${{ env.PLATFORMS }}

      - name: Sign Images
        shell: bash
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          echo 'y' | cosign sign --recursive ${ALPINE_IMAGE_NAME}@${{ steps.alpine-build.outputs.digest }}
          echo 'y' | cosign sign --recursive ${DISTROLESS_IMAGE_NAME}@${{ steps.distroless-build.outputs.digest }}
