name: CI
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

env:
  IMAGE_NAME: ghcr.io/webmeshproj/node
  GO_VERSION: ^1.20

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache-dependency-path: go.sum

      - name: Setup GOPRIVATE
        shell: bash
        run: |
          echo "GOPRIVATE=github.com/webmeshproj" >> $GITHUB_ENV
          git config --global \
            url."https://oauth2:${{ secrets.GOPRIVATE_TOKEN }}@github.com".insteadOf \
            https://github.com

      - name: Run linting
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          args: --timeout 10m
          skip-pkg-cache: true
          skip-build-cache: true

  build-publish:
    name: Build and Publish Artifacts
    runs-on: ubuntu-latest
    needs: [tests]
    permissions:
      contents: "read"
      id-token: "write"
      packages: "write"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          check-latest: true
          cache-dependency-path: go.sum

      - name: Setup GOPRIVATE
        shell: bash
        run: |
          echo "GOPRIVATE=github.com/webmeshproj" >> $GITHUB_ENV
          git config --global \
            url."https://oauth2:${{ secrets.GOPRIVATE_TOKEN }}@github.com".insteadOf \
            https://github.com

      - name: Build Release Binaries
        shell: bash
        run: make dist
